# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Tests/bin/Release/net5.0/'
    jsonTargetFiles: 'appsettings.json'
    xmlTransformationRules: '' # disabled

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'WASalesTax'
    targetPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Mvc/bin/Release/net5.0/'
    publishLocation: 'pipeline'